### PR TITLE
Remove unnecessary function and dependency

### LINKED ISSUE #157: remove test_public_points from run_congruence_checks
Currently, running `run_congruence_checks`includes the function `test_public_points`. The `test_public_points` function will fail with a (warning? error?) if there are GPS point coordinates in metadata and the data are restricted, indicating in the warning message that these metadata points will be exposed to the public.

After the most recent DataStore patch, this is no longer true - GPS coordinates will only be served up to those with permissions to access the files and the GPS component of metadata will not be shared publicly or move up to data.gov, etc.

This test should be removed from the list of tests conducted by `run_congruence_checks` to bring that set of tests back in line with what is needed with datastore. The function should probably be removed entirely from the package, or at least have the documentation updated to indicate that it is no longer relevant.

### PR DESCRIPTION
**Pull request by wright13**
Remove test_public_points and remove arcticdatautils dependency (replace with equivalent fxn from EMLeditor).
I changed the version number to 1.1.0. If that seems reasonable, we may want to do a 1.0.1 release before merging this pr. (Do we usually do github releases for minor versions? If not, disregard).
Closes #157

### CODE REVIEW

**Comment by wright13** [comment]
Oops hold off on merging this - I've confused myself with the arcticdatautils stuff and just saw that you made similar changes in another unmerged PR

**Comment by wright13** [comment]
Also just did what I think will add links for bug reports and source code to the pkgdown site, in response to comments in JOSS review

File: R/required_eml_elements.R [hunk 1]
```diff
@@ -143,19 +143,19 @@ test_by_for_nps <- function(metadata = load_metadata(directory)) {
   nps <- EMLeditor::get_eml_simple(metadata, "byOrForNPS")
   missing_nps <- is.null(nps)
   #error if no by or for nps
-  if (missing_nps) {
```
Comment (RobLBaker) [inline R/required_eml_elements.R:146]: I thought we were using the tidyverse style guide? That includes spaces between the `if` and the conditional statement and between the end of the conditional statement and the opening curly brace:

https://style.tidyverse.org/syntax.html

**Review by RobLBaker — CHANGES_REQUESTED** [review]
All of the actual code changes look great, but it looks like you reverted back away from tidyverse style guide by removing spaces in the opening lines of 'if' statements.  See: https://style.tidyverse.org/syntax.html

File: R/required_eml_elements.R (hunk 1 above)
Comment (wright13) [reply R/required_eml_elements.R:146]: Oh cool, I'm not actually sure how that happened. A lot of stuff in DPchecker needs to be restyled so I'll just do the whole package while I'm at it. I've got other things I need to do this morning, but should have it pushed later today.

Comment (wright13) [reply R/required_eml_elements.R:146]: Just ran styler on the whole package, should be ✨ very tidy ✨ now

**Review by RobLBaker — APPROVED** [review]
Looks great - resolved conflicts and good to merge!
